// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-spr2vGkBf1yhusBn5Z92JrXR679MeLo',
    appId: '1:195153078397:web:5c3d9fe4f05f8f2447a914',
    messagingSenderId: '195153078397',
    projectId: 'trackacademic-c0d1c',
    authDomain: 'trackacademic-c0d1c.firebaseapp.com',
    storageBucket: 'trackacademic-c0d1c.firebasestorage.app',
    measurementId: 'G-F4YP9X5Z83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACTyGR5fN0IWejPwV_1QiHofLnwoAAum4',
    appId: '1:195153078397:android:a637ab6e46e61a4347a914',
    messagingSenderId: '195153078397',
    projectId: 'trackacademic-c0d1c',
    storageBucket: 'trackacademic-c0d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKD_8rz1qmBPFfbAF3Y86kTsNoBmgQY8',
    appId: '1:195153078397:ios:ac03df31e383af0947a914',
    messagingSenderId: '195153078397',
    projectId: 'trackacademic-c0d1c',
    storageBucket: 'trackacademic-c0d1c.firebasestorage.app',
    iosBundleId: 'com.trackademic.trackademic',
  );
}
